In [1]:
import numpy as np

In [2]:
# Vector: 1D Array
# Metrics: 2D Array

In [3]:
list_number = [1, 2, 3, 4, 5]
arr = np.array(list_number)

# 1D Array 
print(arr)

[1 2 3 4 5]


In [4]:
list_number2 = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(list_number2)

# 2D Array
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Same as Range in Python
# Not include 10
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
# 2 X 10 Array with 0
np.zeros(10)
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
# 2 X 10 Array with 1
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
# 1D Array
# 0 to 9
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [9]:
# Matrics identity
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
# Random number distributed between 0 and 1, 2D Array
np.random.rand(10, 2)

array([[0.3457463 , 0.62961365],
       [0.01792042, 0.50936161],
       [0.5517456 , 0.30100714],
       [0.56754487, 0.22743687],
       [0.83647454, 0.06630654],
       [0.89258862, 0.44020696],
       [0.93659706, 0.16754946],
       [0.76345235, 0.67287106],
       [0.00604312, 0.4113067 ],
       [0.39894757, 0.49855636]])

In [11]:
# Return normalize value
np.random.randn(10, 2)

array([[-0.65139394,  0.09881029],
       [ 2.33360567, -0.47352619],
       [-1.36787286, -2.44635052],
       [ 1.060279  , -0.14862796],
       [ 0.02615131, -0.90192197],
       [-0.63395559,  0.77750723],
       [-0.29916877,  0.84057337],
       [ 0.02586698, -0.85624724],
       [ 0.3641117 , -0.43662089],
       [ 1.76202882, -0.86651277]])

In [12]:
np.random.randint(0, 10, 2)

array([4, 0])

In [13]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
rnarr = np.random.randint(0, 50, 10)
rnarr

array([ 0,  0, 12, 44, 40,  2, 11, 32, 40, 25])

In [15]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
rnarr.reshape(5, 2)

array([[ 0,  0],
       [12, 44],
       [40,  2],
       [11, 32],
       [40, 25]])

In [17]:
rnarr.max()

44

In [18]:
rnarr.min()

0

In [19]:
rnarr.sum()

206

In [20]:
# Index of max value
rnarr.argmax()

3

In [21]:
rnarr.argmin()

0

In [22]:
rnarr.shape

(10,)

In [23]:
rnarr.dtype

dtype('int64')

In [24]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr[:2]

array([0, 1])

In [26]:
slice_arr = arr[0:5]
slice_arr[:] = 100
slice_arr

array([100, 100, 100, 100, 100])

In [27]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [28]:
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [29]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [30]:
matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [31]:
matrix_2d[1][1]

5

In [32]:
matrix_2d[1,1]

5

In [33]:
matrix_2d[-2,:2]

array([4, 5])

In [34]:
arr = np.arange(0, 10)

In [35]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
bool_arr = arr > 5

In [37]:
arr[bool_arr]

array([6, 7, 8, 9])

In [38]:
arr[arr > 4]

array([5, 6, 7, 8, 9])

In [39]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [40]:
arr_2d[2:3, 2:3]

array([[22]])

In [41]:
arr = np.arange(0, 10, 1, dtype=np.int64)
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [43]:
arr / 0

/var/folders/82/w4xg6xtd7w50r8bct5xfjktc0000gn/T/ipykernel_19250/3942562399.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr / 0
/var/folders/82/w4xg6xtd7w50r8bct5xfjktc0000gn/T/ipykernel_19250/3942562399.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [44]:
arr ** 2 ** 2

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])

In [45]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [46]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [47]:
np.max(arr)

9

In [48]:
np.min(arr)

0

In [49]:
np.argmax(arr)

9

In [50]:
np.log(arr)

/var/folders/82/w4xg6xtd7w50r8bct5xfjktc0000gn/T/ipykernel_19250/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])