In [1]:
import numpy as np

In [2]:
# Vector: 1D Array
# Metrics: 2D Array

In [3]:
list_number = [1, 2, 3, 4, 5]
arr = np.array(list_number)

# 1D Array 
print(arr)

[1 2 3 4 5]


In [4]:
list_number2 = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(list_number2)

# 2D Array
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Same as Range in Python
# Not include 10
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
# 2 X 10 Array with 0
np.zeros(10)
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
# 2 X 10 Array with 1
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
# 1D Array
# 0 to 9
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [9]:
# Matrics identity
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
# Random number distributed between 0 and 1, 2D Array
np.random.rand(10, 2)

array([[0.31956772, 0.53606336],
       [0.13761869, 0.63698861],
       [0.95956422, 0.49450379],
       [0.79034103, 0.49212744],
       [0.57033277, 0.27944451],
       [0.29532801, 0.71351726],
       [0.12665179, 0.08872445],
       [0.00544763, 0.68808323],
       [0.98725033, 0.03727563],
       [0.24885074, 0.88345293]])

In [11]:
# Return normalize value
np.random.randn(10, 2)

array([[ 0.2340101 ,  0.9674985 ],
       [-0.3010568 ,  0.45825016],
       [ 2.0327288 , -1.00238939],
       [ 0.06322329,  0.95691219],
       [-0.00226471,  0.73687423],
       [-1.04573455, -1.11486598],
       [ 1.69637477,  0.58328828],
       [ 0.08476535,  0.23142718],
       [-0.24516647,  0.16422675],
       [ 0.2257826 , -0.07309277]])

In [12]:
np.random.randint(0, 10, 10)

array([5, 5, 3, 2, 3, 0, 9, 8, 5, 3])

In [13]:
arr = np.arange(0, 25)

In [14]:
ranarr = np.random.randint(0, 50, 10)

In [15]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
ranarr.reshape(5, 2)

array([[12, 40],
       [46, 49],
       [ 9, 11],
       [14, 23],
       [25, 43]])