In [90]:
import numpy as np

In [91]:
# Vector: 1D Array
# Metrics: 2D Array

In [92]:
list_number = [1, 2, 3, 4, 5]
arr = np.array(list_number)

# 1D Array 
print(arr)

[1 2 3 4 5]


In [93]:
list_number2 = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(list_number2)

# 2D Array
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [94]:
# Same as Range in Python
# Not include 10
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [95]:
# 2 X 10 Array with 0
np.zeros(10)
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [96]:
# 2 X 10 Array with 1
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [97]:
# 1D Array
# 0 to 9
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [98]:
# Matrics identity
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [99]:
# Random number distributed between 0 and 1, 2D Array
np.random.rand(10, 2)

array([[0.81271915, 0.15396776],
       [0.88312202, 0.55596077],
       [0.07887641, 0.42978159],
       [0.7657845 , 0.93735161],
       [0.2979575 , 0.24308737],
       [0.54005495, 0.59975647],
       [0.71847862, 0.03187424],
       [0.15709376, 0.73971449],
       [0.02954624, 0.65372957],
       [0.60692521, 0.52319875]])

In [100]:
# Return normalize value
np.random.randn(10, 2)

array([[ 0.46870556, -0.99210569],
       [ 0.02783192,  0.19776832],
       [ 2.22726331, -0.7257172 ],
       [-2.17901179,  0.36657416],
       [-0.31610452,  0.58746214],
       [-0.21992324,  1.19922153],
       [ 0.88107494, -0.20150219],
       [-0.25136152, -1.4177481 ],
       [-0.20234867,  1.03453672],
       [-0.12720651, -0.6659807 ]])

In [101]:
np.random.randint(0, 10, 2)

array([4, 2])

In [102]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [103]:
rnarr = np.random.randint(0, 50, 10)
rnarr

array([31, 27, 33, 45, 14, 48, 11, 34, 15, 40])

In [104]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [105]:
rnarr.reshape(5, 2)

array([[31, 27],
       [33, 45],
       [14, 48],
       [11, 34],
       [15, 40]])

In [106]:
rnarr.max()

48

In [107]:
rnarr.min()

11

In [108]:
rnarr.sum()

298

In [109]:
# Index of max value
rnarr.argmax()

5

In [110]:
rnarr.argmin()

6

In [111]:
rnarr.shape

(10,)

In [112]:
rnarr.dtype

dtype('int64')

In [113]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
arr[:2]

array([0, 1])

In [116]:
slice_arr = arr[0:5]
slice_arr[:] = 100
slice_arr

array([100, 100, 100, 100, 100])

In [117]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [120]:
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [121]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])